import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import React from "react";
import { auth } from "../lib/auth";
import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();

	return (
		<html lang="en">
			<body className="h-svh flex flex-col">
				<Navbar user={session?.user} />
				{children}
				<Toaster />
			</body>
		</html>
	);
}
